//  Men
let products = [
    {id : 1 , title : 'Men\'s long sleeve shirt' , persianTitle : 'پیراهن آستین بلند مردانه' , image : 'https://dkstatics-public.digikala.com/digikala-products/40a4e582ec907dd527ce82bc217dd0f6749d4163_1645807261.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/format,webp/quality,q_90' , category : 'men' , price : 4.25},
    {id : 2 , title : 'Men\'s fabric pants' , persianTitle : 'شلوار پارچه ای مردانه' , image : 'https://dkstatics-public.digikala.com/digikala-products/4a4ab7b42714d9bb4ea88a6cfc11908374d49679_1694538814.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/format,webp/quality,q_90' , category : 'men' , price : 3.8},
    {id : 3 , title : 'Men\'s short sleeve t-shirt' , persianTitle : 'تی شرت آستین کوتاه مردانه' , image : 'https://dkstatics-public.digikala.com/digikala-products/f5f6cb61e87acde8843c32da10f77bfa085540fc_1645852917.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/format,webp/quality,q_90' , category : 'men' , price : 7.25},
    {id : 4 , title : 'Men\'s jeans' , persianTitle : 'شلوار جین مردانه' , image : 'https://dkstatics-public.digikala.com/digikala-products/f572add7383b3401e2d0b9a1389d7305eb871e61_1660744471.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/format,webp/quality,q_90' , category : 'men' , price : 9.37},
    {id : 5 , title : 'Men\'s sweater' , persianTitle : 'پلیور مردانه' , image : 'https://dkstatics-public.digikala.com/digikala-products/a9824c48269951966cd9f5f46a4bf6957883e91f_1639416517.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80' , category : 'men' , price : 2.73},
    {id : 6 , title : 'Men\'s short-sleeved polo shirt' , persianTitle : 'پولوشرت مردانه' , image : 'https://dkstatics-public.digikala.com/digikala-products/24b7150e113e48d5b1b5048c789bb91e04011c34_1600245489.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/format,webp/quality,q_90' , category : 'men' , price : 1},
    {id : 7 , title : 'Men\'s shorts' , persianTitle : 'شلوارک مردانه' , image : 'https://dkstatics-public.digikala.com/digikala-products/afe8418386c2ad0a046343d011b9e3fd4ceb6409_1703593974.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/format,webp/quality,q_90' , category : 'men' , price : 3.17},
    {id : 8 , title : 'Men\'s sweatshirt' , persianTitle : 'سویشرت مردانه' , image : 'https://dkstatics-public.digikala.com/digikala-products/119348221.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/format,webp/quality,q_90' , category : 'men' , price : 3.5},
    {id : 9 , title : 'Men\'s tops' , persianTitle : 'تاپ مردانه' , image : 'https://dkstatics-public.digikala.com/digikala-products/ea992e9e22f43292a465eb173614773fecbce2ed_1702901450.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/format,webp/quality,q_90' , category : 'men' , price : 2.8},
    {id : 10 , title : 'Men\'s jackets' , persianTitle : 'کاپشن مردانه' , image : 'https://dkstatics-public.digikala.com/digikala-products/ecf43ac0a83210e6fb6c3df3d90ba7537f8ada15_1612099141.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/format,webp/quality,q_90' , category : 'men' , price : 11.5},

    {id : 11 , title : '' , persianTitle : '' , image : '' , category : 'women' , price : 1},
    {id : 12 , title : '' , persianTitle : '' , image : '' , category : 'women' , price : 1},
    {id : 13 , title : '' , persianTitle : '' , image : '' , category : 'women' , price : 1},
    {id : 14 , title : '' , persianTitle : '' , image : '' , category : 'women' , price : 1},
    {id : 15 , title : '' , persianTitle : '' , image : '' , category : 'women' , price : 1},
    {id : 16 , title : '' , persianTitle : '' , image : '' , category : 'women' , price : 1},
    {id : 17 , title : '' , persianTitle : '' , image : '' , category : 'women' , price : 1},
    {id : 18 , title : '' , persianTitle : '' , image : '' , category : 'women' , price : 1},
    {id : 19 , title : '' , persianTitle : '' , image : '' , category : 'women' , price : 1},
    {id : 20 , title : '' , persianTitle : '' , image : '' , category : 'women' , price : 1},

    {id : 21 , title : '' , persianTitle : '' , image : '' , category : 'kids' , price : 1},
    {id : 22 , title : '' , persianTitle : '' , image : '' , category : 'kids' , price : 1},
    {id : 23 , title : '' , persianTitle : '' , image : '' , category : 'kids' , price : 1},
    {id : 24 , title : '' , persianTitle : '' , image : '' , category : 'kids' , price : 1},
    {id : 25 , title : '' , persianTitle : '' , image : '' , category : 'kids' , price : 1},
    {id : 26 , title : '' , persianTitle : '' , image : '' , category : 'kids' , price : 1},
    {id : 27 , title : '' , persianTitle : '' , image : '' , category : 'kids' , price : 1},
    {id : 28 , title : '' , persianTitle : '' , image : '' , category : 'kids' , price : 1},
    {id : 29 , title : '' , persianTitle : '' , image : '' , category : 'kids' , price : 1},
    {id : 30 , title : '' , persianTitle : '' , image : '' , category : 'kids' , price : 1},

    {id : 31 , title : '' , persianTitle : '' , image : '' , category : 'shoes' , price : 1},
    {id : 32 , title : '' , persianTitle : '' , image : '' , category : 'shoes' , price : 1},
    {id : 33 , title : '' , persianTitle : '' , image : '' , category : 'shoes' , price : 1},
    {id : 34 , title : '' , persianTitle : '' , image : '' , category : 'shoes' , price : 1},
    {id : 35 , title : '' , persianTitle : '' , image : '' , category : 'shoes' , price : 1},
    {id : 36 , title : '' , persianTitle : '' , image : '' , category : 'shoes' , price : 1},
    {id : 37 , title : '' , persianTitle : '' , image : '' , category : 'shoes' , price : 1},
    {id : 38 , title : '' , persianTitle : '' , image : '' , category : 'shoes' , price : 1},
    {id : 39 , title : '' , persianTitle : '' , image : '' , category : 'shoes' , price : 1},
    {id : 40 , title : '' , persianTitle : '' , image : '' , category : 'shoes' , price : 1},

    {id : 41 , title : '' , persianTitle : '' , image : '' , category : 'accessory' , price : 1},
    {id : 42 , title : '' , persianTitle : '' , image : '' , category : 'accessory' , price : 1},
    {id : 43 , title : '' , persianTitle : '' , image : '' , category : 'accessory' , price : 1},
    {id : 44 , title : '' , persianTitle : '' , image : '' , category : 'accessory' , price : 1},
    {id : 45 , title : '' , persianTitle : '' , image : '' , category : 'accessory' , price : 1},
    {id : 46 , title : '' , persianTitle : '' , image : '' , category : 'accessory' , price : 1},
    {id : 47 , title : '' , persianTitle : '' , image : '' , category : 'accessory' , price : 1},
    {id : 48 , title : '' , persianTitle : '' , image : '' , category : 'accessory' , price : 1},
    {id : 49 , title : '' , persianTitle : '' , image : '' , category : 'accessory' , price : 1},
    {id : 50 , title : '' , persianTitle : '' , image : '' , category : 'accessory' , price : 1},

    {id : 51 , title : '' , persianTitle : '' , image : '' , category : 'hat' , price : 1},
    {id : 52 , title : '' , persianTitle : '' , image : '' , category : 'hat' , price : 1},
    {id : 53 , title : '' , persianTitle : '' , image : '' , category : 'hat' , price : 1},
    {id : 54 , title : '' , persianTitle : '' , image : '' , category : 'hat' , price : 1},
    {id : 55 , title : '' , persianTitle : '' , image : '' , category : 'hat' , price : 1},
    {id : 56 , title : '' , persianTitle : '' , image : '' , category : 'hat' , price : 1},
    {id : 57 , title : '' , persianTitle : '' , image : '' , category : 'hat' , price : 1},
    {id : 58 , title : '' , persianTitle : '' , image : '' , category : 'hat' , price : 1},
    {id : 59 , title : '' , persianTitle : '' , image : '' , category : 'hat' , price : 1},
    {id : 60 , title : '' , persianTitle : '' , image : '' , category : 'hat' , price : 1},

    {id : 61 , title : '' , persianTitle : '' , image : '' , category : 'clothes' , price : 1},
    {id : 62 , title : '' , persianTitle : '' , image : '' , category : 'clothes' , price : 1},
    {id : 63 , title : '' , persianTitle : '' , image : '' , category : 'clothes' , price : 1},
    {id : 64 , title : '' , persianTitle : '' , image : '' , category : 'clothes' , price : 1},
    {id : 65 , title : '' , persianTitle : '' , image : '' , category : 'clothes' , price : 1},
    {id : 66 , title : '' , persianTitle : '' , image : '' , category : 'clothes' , price : 1},
    {id : 67 , title : '' , persianTitle : '' , image : '' , category : 'clothes' , price : 1},
    {id : 68 , title : '' , persianTitle : '' , image : '' , category : 'clothes' , price : 1},
    {id : 69 , title : '' , persianTitle : '' , image : '' , category : 'clothes' , price : 1},
    {id : 70 , title : '' , persianTitle : '' , image : '' , category : 'clothes' , price : 1},

    {id : 71 , title : '' , persianTitle : '' , image : '' , category : 'glasses' , price : 1},
    {id : 72 , title : '' , persianTitle : '' , image : '' , category : 'glasses' , price : 1},
    {id : 73 , title : '' , persianTitle : '' , image : '' , category : 'glasses' , price : 1},
    {id : 74 , title : '' , persianTitle : '' , image : '' , category : 'glasses' , price : 1},
    {id : 75 , title : '' , persianTitle : '' , image : '' , category : 'glasses' , price : 1},
    {id : 76 , title : '' , persianTitle : '' , image : '' , category : 'glasses' , price : 1},
    {id : 77 , title : '' , persianTitle : '' , image : '' , category : 'glasses' , price : 1},
    {id : 78 , title : '' , persianTitle : '' , image : '' , category : 'glasses' , price : 1},
    {id : 79 , title : '' , persianTitle : '' , image : '' , category : 'glasses' , price : 1},
    {id : 80 , title : '' , persianTitle : '' , image : '' , category : 'glasses' , price : 1},
]
