//  Men
let products = [
    {id : 1 , title : '' , image : '' , category : 'men' , price : 1},
    {id : 2 , title : '' , image : '' , category : 'men' , price : 1},
    {id : 3 , title : '' , image : '' , category : 'men' , price : 1},
    {id : 4 , title : '' , image : '' , category : 'men' , price : 1},
    {id : 5 , title : '' , image : '' , category : 'men' , price : 1},
    {id : 6 , title : '' , image : '' , category : 'men' , price : 1},
    {id : 7 , title : '' , image : '' , category : 'men' , price : 1},
    {id : 8 , title : '' , image : '' , category : 'men' , price : 1},
    {id : 9 , title : '' , image : '' , category : 'men' , price : 1},
    {id : 10 , title : '' , image : '' , category : 'men' , price : 1},

    {id : 11 , title : '' , image : '' , category : 'women' , price : 1},
    {id : 12 , title : '' , image : '' , category : 'women' , price : 1},
    {id : 13 , title : '' , image : '' , category : 'women' , price : 1},
    {id : 14 , title : '' , image : '' , category : 'women' , price : 1},
    {id : 15 , title : '' , image : '' , category : 'women' , price : 1},
    {id : 16 , title : '' , image : '' , category : 'women' , price : 1},
    {id : 17 , title : '' , image : '' , category : 'women' , price : 1},
    {id : 18 , title : '' , image : '' , category : 'women' , price : 1},
    {id : 19 , title : '' , image : '' , category : 'women' , price : 1},
    {id : 20 , title : '' , image : '' , category : 'women' , price : 1},

    {id : 21 , title : '' , image : '' , category : 'kids' , price : 1},
    {id : 22 , title : '' , image : '' , category : 'kids' , price : 1},
    {id : 23 , title : '' , image : '' , category : 'kids' , price : 1},
    {id : 24 , title : '' , image : '' , category : 'kids' , price : 1},
    {id : 25 , title : '' , image : '' , category : 'kids' , price : 1},
    {id : 26 , title : '' , image : '' , category : 'kids' , price : 1},
    {id : 27 , title : '' , image : '' , category : 'kids' , price : 1},
    {id : 28 , title : '' , image : '' , category : 'kids' , price : 1},
    {id : 29 , title : '' , image : '' , category : 'kids' , price : 1},
    {id : 30 , title : '' , image : '' , category : 'kids' , price : 1},

    {id : 31 , title : '' , image : '' , category : 'shoes' , price : 1},
    {id : 32 , title : '' , image : '' , category : 'shoes' , price : 1},
    {id : 33 , title : '' , image : '' , category : 'shoes' , price : 1},
    {id : 34 , title : '' , image : '' , category : 'shoes' , price : 1},
    {id : 35 , title : '' , image : '' , category : 'shoes' , price : 1},
    {id : 36 , title : '' , image : '' , category : 'shoes' , price : 1},
    {id : 37 , title : '' , image : '' , category : 'shoes' , price : 1},
    {id : 38 , title : '' , image : '' , category : 'shoes' , price : 1},
    {id : 39 , title : '' , image : '' , category : 'shoes' , price : 1},
    {id : 40 , title : '' , image : '' , category : 'shoes' , price : 1},

    {id : 41 , title : '' , image : '' , category : 'accessory' , price : 1},
    {id : 42 , title : '' , image : '' , category : 'accessory' , price : 1},
    {id : 43 , title : '' , image : '' , category : 'accessory' , price : 1},
    {id : 44 , title : '' , image : '' , category : 'accessory' , price : 1},
    {id : 45 , title : '' , image : '' , category : 'accessory' , price : 1},
    {id : 46 , title : '' , image : '' , category : 'accessory' , price : 1},
    {id : 47 , title : '' , image : '' , category : 'accessory' , price : 1},
    {id : 48 , title : '' , image : '' , category : 'accessory' , price : 1},
    {id : 49 , title : '' , image : '' , category : 'accessory' , price : 1},
    {id : 50 , title : '' , image : '' , category : 'accessory' , price : 1},

    {id : 51 , title : '' , image : '' , category : 'hat' , price : 1},
    {id : 52 , title : '' , image : '' , category : 'hat' , price : 1},
    {id : 53 , title : '' , image : '' , category : 'hat' , price : 1},
    {id : 54 , title : '' , image : '' , category : 'hat' , price : 1},
    {id : 55 , title : '' , image : '' , category : 'hat' , price : 1},
    {id : 56 , title : '' , image : '' , category : 'hat' , price : 1},
    {id : 57 , title : '' , image : '' , category : 'hat' , price : 1},
    {id : 58 , title : '' , image : '' , category : 'hat' , price : 1},
    {id : 59 , title : '' , image : '' , category : 'hat' , price : 1},
    {id : 60 , title : '' , image : '' , category : 'hat' , price : 1},

    {id : 61 , title : '' , image : '' , category : 'clothes' , price : 1},
    {id : 62 , title : '' , image : '' , category : 'clothes' , price : 1},
    {id : 63 , title : '' , image : '' , category : 'clothes' , price : 1},
    {id : 64 , title : '' , image : '' , category : 'clothes' , price : 1},
    {id : 65 , title : '' , image : '' , category : 'clothes' , price : 1},
    {id : 66 , title : '' , image : '' , category : 'clothes' , price : 1},
    {id : 67 , title : '' , image : '' , category : 'clothes' , price : 1},
    {id : 68 , title : '' , image : '' , category : 'clothes' , price : 1},
    {id : 69 , title : '' , image : '' , category : 'clothes' , price : 1},
    {id : 70 , title : '' , image : '' , category : 'clothes' , price : 1},

    {id : 71 , title : '' , image : '' , category : 'glasses' , price : 1},
    {id : 72 , title : '' , image : '' , category : 'glasses' , price : 1},
    {id : 73 , title : '' , image : '' , category : 'glasses' , price : 1},
    {id : 74 , title : '' , image : '' , category : 'glasses' , price : 1},
    {id : 75 , title : '' , image : '' , category : 'glasses' , price : 1},
    {id : 76 , title : '' , image : '' , category : 'glasses' , price : 1},
    {id : 77 , title : '' , image : '' , category : 'glasses' , price : 1},
    {id : 78 , title : '' , image : '' , category : 'glasses' , price : 1},
    {id : 79 , title : '' , image : '' , category : 'glasses' , price : 1},
    {id : 80 , title : '' , image : '' , category : 'glasses' , price : 1},
]
